/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmanagement;

import DialogBox.DlgAddRes;
import DialogBox.DlgAddTask;
import DialogBox.DlgNewProject;
import DialogBox.DlgOpen;
import DialogBox.DlgProjectInformation;
import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public final class FrmSub extends javax.swing.JFrame {

    /**
     * Creates new form FrmTask
     */
    DBConnection db = new DBConnection();
    Connection con;
    Statement stat;
    ResultSet result;
    String sql;

    public FrmSub(String PN) {
        SetTheme st = new SetTheme();
        initComponents();
        setLocationRelativeTo(null);
        con = db.openConnection();
        showDataToTable1(PN);
        showDataToTable2(PN);

        Container Content = getContentPane();
        Content.setBackground(Color.white);
    }
    DefaultTableModel Tmodel1;
    DefaultTableModel Tmodel2;

    public FrmSub() {
        SetTheme st = new SetTheme();
        initComponents();
        setLocationRelativeTo(null);
        con = db.openConnection();
        showDataToTable1();
        showDataToTable2();
        Container Content = getContentPane();
        Content.setBackground(Color.white);
    }

    public void showDataToTable1(String PN) {
        try {
            String[] ColumnName = {"Id", "Name", "Duration", "Start", "Finish"};
            Tmodel1 = new DefaultTableModel(null, ColumnName);

            stat = con.createStatement();
            Statement stat2;
            Connection con2;
            con2 = db.openConnection();
            stat2 = con2.createStatement();
            String sql2 = "SELECT * FROM project where name_project='" + PN + "'";
            ResultSet rs = stat2.executeQuery(sql2);
            rs.first();
            String id = rs.getString(1);
            sql = "SELECT * FROM task where id_project = '" + id + "'";
            result = stat.executeQuery(sql);

            while (result.next()) {
                String name = result.getString(3);
                String idtask = result.getString(2);
                String duration = result.getString(4);
                String start = result.getString(5);
                String finish = result.getString(6);

                Tmodel1.addRow(new String[]{idtask, name, duration, start, finish});
            }

            tbl_task.setModel(Tmodel1);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Failed To Show Data");
        }

    }

    public void showDataToTable1() {
        String[] ColumnName = {"Id", "Name", "Duration", "Start", "Finish"};
        Tmodel1 = new DefaultTableModel(null, ColumnName);

        tbl_task.setModel(Tmodel1);
    }

    public void showDataToTable2() {
        String[] ColumnName = {"Id", "Name", "Type", "Initials", "Group"};
        Tmodel2 = new DefaultTableModel(null, ColumnName);

        tbl_resource.setModel(Tmodel2);
    }

    public void showDataToTable2(String PN) {
        try {
            String[] ColumnName = {"Id", "Name", "Type", "Initials", "Group"};
            Tmodel2 = new DefaultTableModel(null, ColumnName);
            stat = con.createStatement();
            Statement stat2;
            Connection con2;
            con2 = db.openConnection();
            stat2 = con2.createStatement();
            String sql2 = "SELECT * FROM project where name_project='" + PN + "'";
            ResultSet rs = stat2.executeQuery(sql2);
            rs.first();
            String id = rs.getString(1);
            stat = con.createStatement();
            sql = "SELECT * FROM resource where id_project ='" + id + "'";
            result = stat.executeQuery(sql);

            while (result.next()) {
                String idres = result.getString(2);
                String name = result.getString(3);
                String type = result.getString(4);
                String initials = result.getString(7);
                String group = result.getString(8);

                Tmodel2.addRow(new String[]{idres, name, type, initials, group});
            }

            tbl_resource.setModel(Tmodel2);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Failed To Show Data");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_task = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_resource = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_File = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Menu_Item_Exit = new javax.swing.JMenuItem();
        Menu_Project = new javax.swing.JMenu();
        Menu_Item_PI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sproj V 1.0");

        tbl_task.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_task);

        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btndelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndelete)
                    .addComponent(jButton5)
                    .addComponent(jButton1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Task", jPanel1);

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tbl_resource.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_resource);

        jButton3.setText("add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Resource", jPanel2);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hias.png"))); // NOI18N

        jMenuBar1.setForeground(new java.awt.Color(212, 208, 200));

        Menu_File.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Main Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Menu_File.add(jMenuItem1);

        Menu_Item_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.ALT_MASK));
        Menu_Item_Exit.setText("Exit");
        Menu_Item_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Item_ExitActionPerformed(evt);
            }
        });
        Menu_File.add(Menu_Item_Exit);

        jMenuBar1.add(Menu_File);

        Menu_Project.setText("Project");

        Menu_Item_PI.setText("Project Information");
        Menu_Item_PI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Item_PIActionPerformed(evt);
            }
        });
        Menu_Project.add(Menu_Item_PI);

        jMenuBar1.add(Menu_Project);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_Item_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Item_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Menu_Item_ExitActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try {
            // TODO add your handling code here:
            int row = tbl_task.getSelectedRow();
            String id = tbl_task.getValueAt(row, 0).toString();
            stat = con.createStatement();
            stat.executeUpdate("Delete From task where id_task ='" + id + "'");
            JOptionPane.showMessageDialog(null, "Delete Success");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Delete Failed");
        }

    }//GEN-LAST:event_btndeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DlgAddTask dat = new DlgAddTask(null, true);
        dat.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String id = null;
        try {
            // TODO add your handling code here:
            int row = tbl_resource.getSelectedRow();
            id = tbl_resource.getValueAt(row, 0).toString();
            stat = con.createStatement();
            stat.executeUpdate("Delete From resource where id_resource ='" + id + "'");
            JOptionPane.showMessageDialog(null, "Delete Success");
        } catch (Exception ex) {
            System.out.println(id);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DlgAddRes dat = new DlgAddRes(null, true);
        dat.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Menu_Item_PIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Item_PIActionPerformed
        // TODO add your handling code here:
        new DlgProjectInformation(null, true).setVisible(true);
    }//GEN-LAST:event_Menu_Item_PIActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            String[] ColumnName = {"Id", "Name", "Type", "Initials", "Group"};
            Tmodel2 = new DefaultTableModel(null, ColumnName);
            stat = con.createStatement();
            Statement stat2;
            Connection con2;
            con2 = db.openConnection();
            stat2 = con2.createStatement();
            String sql2 = "SELECT * FROM project where name_project='" + projectmanagement.main.getName_Project() + "'";
            ResultSet rs = stat2.executeQuery(sql2);
            rs.first();
            String id = rs.getString(1);
            stat = con.createStatement();
            sql = "SELECT * FROM resource where id_project ='" + id + "'";
            result = stat.executeQuery(sql);

            while (result.next()) {
                String idres = result.getString(2);
                String name = result.getString(3);
                String type = result.getString(4);
                String initials = result.getString(7);
                String group = result.getString(8);

                Tmodel2.addRow(new String[]{idres, name, type, initials, group});
            }

            tbl_resource.setModel(Tmodel2);
        } catch (SQLException ex) {
            Logger.getLogger(FrmSub.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            String[] ColumnName = {"Id", "Name", "Duration", "Start", "Finish"};
            Tmodel1 = new DefaultTableModel(null, ColumnName);

            stat = con.createStatement();
            Statement stat2;
            Connection con2;
            con2 = db.openConnection();
            stat2 = con2.createStatement();
            String sql2 = "SELECT * FROM project where name_project='" + projectmanagement.main.getName_Project() + "'";
            ResultSet rs = stat2.executeQuery(sql2);
            rs.first();
            String id = rs.getString(1);
            sql = "SELECT * FROM task where id_project = '" + id + "'";
            result = stat.executeQuery(sql);

            while (result.next()) {
                String name = result.getString(3);
                String idtask = result.getString(2);
                String duration = result.getString(4);
                String start = result.getString(5);
                String finish = result.getString(6);

                Tmodel1.addRow(new String[]{idtask, name, duration, start, finish});
            }

            tbl_task.setModel(Tmodel1);
        } catch (SQLException ex) {
            Logger.getLogger(FrmSub.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FrmMain().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmSub().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_File;
    private javax.swing.JMenuItem Menu_Item_Exit;
    private javax.swing.JMenuItem Menu_Item_PI;
    private javax.swing.JMenu Menu_Project;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_resource;
    private javax.swing.JTable tbl_task;
    // End of variables declaration//GEN-END:variables
}
